name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

