name: CI

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build:
    name: build (node ${{ matrix.node }})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node: [18, 20]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node }}
          cache: npm

      - name: Install deps
        run: npm ci

      - name: Type check
        run: npm run type-check

      - name: Build
        run: npm run build

      - name: Check circular dependencies
        run: npx madge --circular --extensions ts src/

      - name: Run core tests
        run: npm run test

      - name: Run API stability tests
        run: npm run test:api

      - name: Run MDM validator tests
        run: npm run test:validator

      - name: Check bundle size
        run: |
          BUNDLE_SIZE=$(stat -c%s dist/mds-core.esm.js)
          MAX_SIZE=$((185 * 1024))  # 185 KB in bytes (increased for v5.2.2 - AGI-ready with no lazy loading)
          echo "Bundle size: $(($BUNDLE_SIZE / 1024)) KB"
          echo "Maximum allowed: 185 KB"
          if [ $BUNDLE_SIZE -gt $MAX_SIZE ]; then
            echo "❌ Bundle size exceeds 185 KB limit!"
            exit 1
          fi
          echo "✅ Bundle size within limits"

